name: Manual test runner

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Choose browser
        default: Chrome
        options:
        - Chrome
        - Firefox
        - Edge

jobs:
  Execute-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Chrome Browser
        if: "contains(github.event.inputs.browser, 'Chrome')"
        run:   |
            chmod +x ./SeleniumProject/scripts/InstallChrome.sh
                        ./SeleniumProject/scripts/InstallChrome.sh
      - name: Install Firefox Browser
        if: "contains(github.event.inputs.browser, 'Firefox')"
        run:   |
            chmod +x ./SeleniumProject/scripts/InstallFirefox.sh
                        ./SeleniumProject/scripts/InstallFirefox.sh
      - name: Install Edge Browser
        if: "contains(github.event.inputs.browser, 'Edge')"
        run:   |
            chmod +x ./SeleniumProject/scripts/InstallEdge.sh
                        ./SeleniumProject/scripts/InstallEdge.sh
      - name: Build and install with Maven
        run: mvn clean install --file ./SeleniumProject/pom.xml -DskipTests
      - name: Initialize App server
        run: mvn test --file ./SeleniumProject/pom.xml -DsuiteFile=initializeappserversuite.xml -Dbrowser=${{ inputs.browser }} -Dheadless=yes
      - name: Run all E2E tests
        run: mvn test --file ./SeleniumProject/pom.xml -DsuiteFile=testsuite.xml -Dbrowser=${{ inputs.browser }} -Dheadless=yey
      - name: Remove test data
        run: mvn test --file ./SeleniumProject/pom.xml -DsuiteFile=removetestdatasuite.xml -Dbrowser=${{ inputs.browser }} -Dheadless=yes
